version: "3.7"
services: 
  db:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
      POSTGRES_USER: ${DB_DEV_USERNAME}
      POSTGRES_DB: ${DB_DEV_NAME}
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  redis:
    container_name: redis
    restart: always
    image: redis
    command: redis-server
    ports:
       - '6378:6379'

  web:
    container_name: nomad
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=${DB_DEV_PASSWORD}
      - POSTGRES_USER=${DB_DEV_USERNAME}
      - POSTGRES_DB=${DB_DEV_NAME}
      - NODE_ENV=production
      - DB_HOST=db
      - REDIS_HOST=redis
    environment: 
      POSTGRES_PASSWORD: nosenti
      POSTGRES_USER: postgres
      POSTGRES_DB: barefoot-nomad
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '8081:5432'
    
  web:
    container_name: nomad
    build: .
    depends_on: 
      - db
    ports:
      - "5000:3000"
    links:
      - db
    external_links: 
      - db
    environment: 
      DATABASE_URL: postgres://postgres:nosenti@db:5432/barefoot-nomad
    
